trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  tags:
    include:
    - '*'


jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'

  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      pip install --upgrade setuptools
      pip install -e .
    displayName: Install keepa

  - script: |
      pip install -r requirements_test.txt
      pip install pytest-azurepipelines
      pytest -v --cov keepa --cov-report html
    displayName: 'Test Core API'
    env:
      KEEPAKEY: $(keepa.key)
      WEAKKEEPAKEY: $(keepa.weakkey)

  - script: |
      bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload coverage to codecov.io'
    condition: eq(variables['python.version'], '3.7')

  - script: |
      pip install twine
      python setup.py sdist
      twine upload --skip-existing dist/keepa*.gz
    displayName: 'Upload to PyPi'
    condition: and(eq(variables['python.version'], '3.7'), contains(variables['Build.SourceBranch'], 'refs/tags/'))
    env:
      TWINE_USERNAME: $(twine.username)
      TWINE_PASSWORD: $(twine.password)
      TWINE_REPOSITORY_URL: "https://upload.pypi.org/legacy/"

